# Generated by Django 5.1.3 on 2025-04-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0011_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='push_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
