# Generated by Django 5.1.3 on 2025-04-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0013_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(max_length=256),
        ),
    ]
